# https://packit.dev/docs/configuration/

specfile_path: fido-device-onboard.spec

files_to_sync:
    - fido-device-onboard.spec
    - .packit.yaml

upstream_package_name: fido-device-onboard
downstream_package_name: fido-device-onboard

upstream_tag_template: v{version}
copy_upstream_release_description: true

srpm_build_deps:
- cargo

actions:
  create-archive:
  - bash -c "sed -i -r \"s/Source0:.+/Source0:\ fido-device-onboard-rs-${PACKIT_PROJECT_VERSION}.tar/\" fido-device-onboard.spec"
  - bash -c "sed -i \"/Source1/d\" fido-device-onboard.spec"
  - bash -c "git archive --prefix=fido-device-onboard-rs-${PACKIT_PROJECT_VERSION}/ --format=tar HEAD > fido-device-onboard-rs-${PACKIT_PROJECT_VERSION}.tar"
  - bash -c "tar -xvf fido-device-onboard-rs-${PACKIT_PROJECT_VERSION}.tar"
  - bash -c "ls -1 ./fido-device-onboard-rs-${PACKIT_PROJECT_VERSION}.tar"
  fix-spec-file:
  - "cat fido-device-onboard.spec"

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-development-aarch64
  - fedora-development
  - fedora-latest
  - fedora-latest-aarch64
- job: copr_build
  trigger: commit
  branch: main
  owner: "@fedora-iot" # copr repo namespace
  project: fedora-iot  # copr repo name so you can consume the builds
  targets:
  - fedora-development-aarch64
  - fedora-development
  - fedora-latest
  - fedora-latest-aarch64
