---
# https://packit.dev/docs/configuration/

specfile_path: fido-device-onboard.spec

files_to_sync:
  - src:
      - ".packit.yaml"
      - "fido-device-onboard.spec"
      - "fido-device-onboard-rs-*-vendor-patched.tar.xz"
      - "patches/0001-Revert-chore-use-git-fork-for-aws-nitro-enclaves-cos.patch"
    dest: .

upstream_package_name: fido-device-onboard
downstream_package_name: fido-device-onboard

upstream_tag_template: v{version}
copy_upstream_release_description: true

srpm_build_deps:
  - cargo
  - openssl-devel

packages:
  fido-device-onboard-fedora:
    downstream_package_name: fido-device-onboard
    upstream_package_name: fido-device-onboard
  fido-device-onboard-centos:
    downstream_package_name: fido-device-onboard
    upstream_package_name: fido-device-onboard
    pkg_tool: centpkg

actions:
    pre-sync:
        - bash -c "make vendor VERSION=${PACKIT_PROJECT_VERSION}"
        - bash -c "git restore Cargo.lock"
    create-archive:
        - bash -c "make packit-create-archive VERSION=${PACKIT_PROJECT_VERSION}"

jobs:
    - &fdo_copr_build
      job: copr_build
      trigger: pull_request
      targets:
          centos-stream-9: {}
          fedora-latest-stable: {}
          fedora-latest: {}
          fedora-rawhide: {}

    - job: tests
      trigger: pull_request
      identifier: onboarding
      fmf_path: test/fmf
      tmt_plan: plans/onboarding
      targets:
          centos-stream-9: {}
          fedora-latest-stable: {}
          fedora-latest: {}
          fedora-rawhide: {}

    - job: sync_from_downstream
      trigger: commit

    - job: propose_downstream
      trigger: release
      packages: [fido-device-onboard-fedora]
      dist_git_branches:
        - fedora-development
        - fedora-latest-stable

    - job: propose_downstream
      trigger: release
      packages: [fido-device-onboard-centos]
      dist_git_branches:
        - c10s
        - c9s

    - job: koji_build
      trigger: commit
      allowed_pr_authors: [all_committers]
      dist_git_branches:
        - fedora-development
        - fedora-latest-stable

    - job: bodhi_update
      trigger: commit
      allowed_builders: [all_committers]
      dist_git_branches:
        - fedora-development
        - fedora-latest-stable

    - <<: *fdo_copr_build
      trigger: commit
      branch: main
      owner: "@fedora-iot"  # copr repo namespace
      project: fedora-iot   # copr repo name so you can consume the builds
...
